//
//  File.swift
//  
//
//  Created by linhey on 2024/4/6.
//

import Foundation
import XCTest
import OpenAICore

final class TextSplitterTests: XCTestCase {
    
    func test_split_paper() async throws {
     let text = """
HF is a complex clinical syndrome caused by abnormal changes in cardiac structure and/or function via various mechanisms, which results in ventricular systolic and/or diastolic dysfunction. It is a severe manifestation or terminal stage of various heart diseases. In the early stage of HF, the stress response signiﬁ cantly increases the levels of epinephrine, glucagon, and glucocorticoids to above the physiological ranges. In the later stage, due to low cardiac output, the adrenal cortex is ischemic and hypoxic due to hypoperfusion, so its function of synthesizing corticosteroids is impaired, resulting in decreased blood cortisol.
 
Glucocorticoids are steroid compounds secreted by the zona fasciae in the adrenal cortex and is mostly regulated by the hypothalamic-pituitary-adrenal axis . Physiological doses of glucocorticoids can regulate substance metabolism in the body and maintain its life activities. Supraphysiological doses of glucocorticoids have anti-inﬂammatory, anti-infective, antishock, and immunosuppressive effects, so they are widely used in clinical practice. The effects of standard treatment drugs are often less strong in the late stage of HF than in the early stage. The adrenal glands are often in an excited state due to repeated acute HF attacks, which eventually leads to a decrease in glucocorticoid secretion, especially in elderly patients with HF accompanied by adrenal insufﬁciency and infection.
 
Various animal experiments have found that glucocorticoids can enhance myocardial contractility, which occurs via numerous mechanisms. First, the increased release or enhanced effect of endogenous catecholamines indirectly leads to increased myocardial contractility . Second, it may also be caused by β-adrenergic receptor upregulation in the myocardium . Glucocorticoids can also protect kidney function. Previous studies have found that glucocorticoids dilate renal blood vessels, enhance the sensitivity of nephrons to diuretics, and increase the GFR , via the following mechanisms: First, glucocorticoids upregulate natriuretic peptide receptor A expression in the inner medullary collecting duct cells to enhance the sensitivity of the kidneys to natriuretic peptides and promote the diuretic effect in patients with HF . Second, glucocorticoids reduce the production and secretion of vasopressin, and downregulate arginine vasopressin receptor expression; the production of prostaglandins, nitric oxide, and dopamine is also increased, resulting in improved renal blood ﬂow and GFR . Third, an animal study found that glucocorticoids somewhat affected the synthesis and release of atrial natriuretic peptide (ANP), up-regulating ANP receptors in vascular endothelial cells . Likewise, studies have found that glucocorticoids may modulate ANP-mediated natriuresis and diuresis in humans . Glucocorticoids also enhance pulmonary edema clearance.
 
Glucocorticoids can adjust the activity of alveolar epithelial Na+ channel and Na+-K+ ATPase, increase the tension in pulmonary blood vessels, and reduce the permeability of capillaries, so it can increase alveolar ﬂuid clearance and accelerate the curing of pulmonary edema.
 
However, excessive cortisol secretion and the use of various synthetic glucocorticoids increase the incidence rates of diabetes and cardiovascular disease . Glucocorticoid use in non-diabetic patients increases their risk of developing diabetes by two-to fourfold . The mechanism of glucocorticoid-induced diabetes involves increasing insulin resistance, thereby affecting the glucose metabolism process, which is similar to the mechanism of type 2 diabetes. In the liver, increased insulin resistance can increase basal glucose production. Insulin also promotes intracellular glucose utilization by stimulating glucose transporter type 4, but glucocorticoids interfere with these signaling pathways and with glycogen synthesis. The above two mechanisms may lead to abnormal glucose metabolism and increase blood glucose levels . An observational study found that low-density lipoprotein (LDL) was elevated after glucocorticoid therapy in patients with asthma, heart transplant, kidney transplant, and rheumatoid arthritis, which led to abnormal lipid metabolism . An in vitro study found that hydrocortisone and dexamethasone alter LDL degradation in ﬁbroblasts and macrophages, which may contribute to atherosclerosis .
 
Dexamethasone is also known to cause cardiotoxicity . Studies have found that long-term dexamethasone use may lead to cardiac ﬁbrosis, increased norepinephrine-induced vasoconstriction, increased apoptosis, and decreased angiogenesis . Dexamethasone can also cause cphy, which is an adaptive ardiac hypertrochange in response to dexamethasone-induced hypertension . Bézard  assessed the effect of dexamethasone on cardiac function using the Langendorff perfused heart model in healthy rats. The model is free from other confounding factors, allowing for precise studies of how the heart responds to dexamethasone . Their study found that dexamethasone signiﬁcantly reduced overall left ventricle (LV) function, as well as being caused LV systolic and diastolic dysfunction to various degrees. It is particularly interesting that the above-mentioned changes were also observed in healthy rats . Similarly, de Salvi Guimarães et al. found that dexamethasone-treated rats also developed multiple circulatory complications, including increased blood pressure, myocardial ﬁbrosis, and cardiomyocyte apoptosis, which led to myocardial remodeling and diastolic dysfunction. That study also conﬁrmed that the mechanisms underlying these changes included impaired calcium handling and activation of the calcineurin signaling pathway. It has also been found that systemic glucocorticoid use may increase the risk of deep-vein thrombosis, especially in patients with pulmonary embolism . Despite the effects of glucocorticoids on sodium excretion, diuresis, and increased GFR, glucocorticoid use increased the likelihood of non- acute complications such as diabetes, dyslipidemia, cardiotoxicity, and deep-vein thrombosis, which will be detrimental to the prognosis of patients with HF.
 
In this study, the WBC count was higher in the glucocorticoid group than in the non-glucocorticoid group (13.06 ± 20.53 vs. 11.76 ± 9.66 k/μl), as was the proportion of patients with chronic respiratory disease (45.7% vs. 28.8%). This suggests that the higher risk of death in the glucocorticoid group is caused by glucocorticoid-use-related diseases, such as chronic respiratory disease and infection. Some studies also found that serum inﬂammatory markers were associated with the incidence of cardiovascular events, and disease activity was directly related to the occurrence of cardiovascular events . We found that the association between glucocorticoid use and increased mortality in patients with HF persisted after adjusting for chronic respiratory disease and WBC counts.
 
We performed subgroup analyses of age, sex, congestive HF, diabetes, hypertension, chronic lung disease, kidney failure, liver disease, peptic ulcer, obesity, and anemia. The results indicated that there was no interaction between stratiﬁcation variables and glucocorticoid exposure. The results of each subgroup analysis and the overall results also remained consistent at different follow-up times, indicating that our results were robust.
 
The highlight of our study was the division of follow-up into two time periods to more precisely account for the occurrence of outcome events. This study had some limitations. First, database limitations meant that we did not perform a subgroup analysis of total glucocorticoid dosage and administration duration. Second, the left ventricle ejection fraction was not analyzed in the study because it had more than 40% missing values. In addition, our study is a single-center study, and we hope that in future studies, multi-center studies can be conducted to obtain more information.
 
In conclusion, this retrospective study of a large database found that glucocorticoid use was associated with increased all-cause mortality in critically ill patients with HF. Our ﬁndings suggest that the use of glucocorticoids should not be recommended for critically ill patients with HF, but this requires further validation in prospective studies or randomized controlled trials.
"""
        for result in try await RecursiveCharacterTextSplitter(separatorSet: .paper).split(text: text).map(\.text) {
            print("==>", result.trimmingCharacters(in: .whitespacesAndNewlines))
        }
    }
    
}
